public/css/style.css
src/app/globals.css
src/components/dashboard/card/UserChatList1.jsx
src/components/dashboard/element/MessageBox.jsx
src/components/user/UserImage.jsx
src/hook/useChatSystem.js
src/lib/graphql/queries/main/chat/index.js
src/lib/graphql/queries/main/message/index.js
src/utils/timeAgo.js

This pull request introduces several updates to improve the user interface and functionality of the chat system, focusing on styling, user experience enhancements, and code refactoring. Key changes include updated CSS for better responsiveness and aesthetics, enhancements to the chat message display logic, and the addition of utility functions for handling URLs in messages.
* **Improved message container styling**: Added borders, updated background colors, and modified padding for better visual clarity (`public/css/style.css`). [[1]](diffhunk://#diff-83372de0b8a443dc64be5edecd0b3537dafbe92799d70cb01c8d6c4d38b7562fR1312) [[2]](diffhunk://#diff-83372de0b8a443dc64be5edecd0b3537dafbe92799d70cb01c8d6c4d38b7562fR1323-R1327) [[3]](diffhunk://#diff-83372de0b8a443dc64be5edecd0b3537dafbe92799d70cb01 …

ML8-25 Chat design - Messages

---

src/hook/useChatSystem.js

This pull request refactors the `useChatSystem` hook to ensure chat lists are consistently sorted by the most recent message timestamp. The changes introduce a reusable helper function for sorting chats and apply it across various parts of the hook to maintain proper order after updates.
* **Introduced `sortChatsByLatestMessage` helper function**: Added a reusable function to sort chats by the most recent message timestamp, considering either the `lastMessage.createdAt` or `updatedAt` fields. This improves code readability and reduces duplication. (`src/hook/useChatSystem.js`, [src/hook/useChatSystem.jsR9-R24](diffhunk://#diff-8ef740202b650f81949d3e6ab9dd6b7959641d1e9745d6468b902a2dc8043cabR9-R24))
* **Initial chat list sorting**: Updated the `chatList` state initialization to sort the …

ML8-28 Users list order - Messages

---

public/css/style.css
src/app/(dashboard)/dashboard/messages/page.jsx
src/components/dashboard/element/MessageBox.jsx
src/components/dashboard/section/MessageInfo.jsx
src/hook/useChatSystem.js
src/lib/graphql/queries/main/chat/index.js
src/lib/graphql/queries/main/message/index.js

This pull request introduces pagination, lazy loading, and improved scrolling behavior for the messaging interface. Key changes include adding pagination metadata, implementing lazy loading for chat lists and messages, and enhancing the user experience with better scroll handling. Additionally, minor UI adjustments and code cleanup were performed.
* Added pagination metadata (`page`, `pageSize`, `pageCount`, `total`) to the `MessagesPage` and `MessageInfo` components to support paginated data fetching for chat lists and messages. (`src/app/(dashboard)/dashboard/messages/page.jsx` - [[1]](diffhunk://#diff-f1dd5b21b2acf062408b93124e3d3f1550523aad4d5766f7ede38bd41ca7fe26R18-R35) [[2]](diffhunk://#diff-f1dd5b21b2acf062408b93124e3d3f1550523aad4d5766f7ede38bd41ca7fe26R53-R57) …

ML8-27 Chat & Messages Pagination - Messages

---

src/app/(home)/page.jsx
src/lib/cache/config.js

This pull request focuses on improving caching strategies across the application by introducing consistent TTL (time-to-live) values for various cache keys and ensuring proper caching for data fetches in the home page. The changes aim to optimize performance and reduce redundant data fetching.
* Updated the TTL values for existing cache keys in `CACHE_CONFIG` to shorter durations for more frequent updates, such as reducing `USERS` from 1 hour to 5 minutes and `SERVICES` from 1 day to 10 minutes. Added new cache keys (`HOME_SERVICES`, `HOME_FREELANCERS`, `FEATURED_CATEGORIES`, `ACTIVE_TOP`) with specific TTL values to support better caching granularity. (`src/lib/cache/config.js`, [src/lib/cache/config.jsL8-R48](diffhunk://#diff-dc4699fd7e18eb630844d1029b93ae71404176f1ddfc94f68061aa168a2be5 …

ML8-21 Homepage/mega menu guests cache - Bugs

---

src/app/api/graphql/route.js

This pull request improves error handling in the `POST` method of the `src/app/api/graphql/route.js` file. The changes ensure that the response from the GraphQL API is validated before processing and provide better debugging information in case of errors.
* Added a check to verify if the `response.ok` flag is true before attempting to parse the response as JSON. If the response is not OK, an error message is logged, and a JSON error response is returned with the appropriate status code.
* Introduced a `try-catch` block to handle JSON parsing errors. If parsing fails, the response text is logged (up to the first 200 characters) for debugging purposes, and a JSON error response is returned with a 500 status code.

ML8-31 Route /api/graphql errors - Bugs

---

src/middleware.js

This pull request introduces a safeguard to handle cases where a token exists but no freelancer profile is associated with it. The middleware now redirects users to the login page with an error message and clears the token cookie in such scenarios.
Key changes in `src/middleware.js`:
* Added a check to detect when a token is present but no freelancer profile exists.
* Introduced a redirect to the `/login` page with an error message (`error=missing_profile`) in such cases.
* Implemented logic to clear the token cookie by setting it to expire immediately, ensuring proper cleanup.

ML8-30 Middleware error - Bugs

---

src/components/inputs/Input.jsx
src/components/ui/forms/RegisterForm.jsx
src/utils/InputFormats/formats.js

This pull request introduces a new `formatUsername` function to replace the existing `allowOnlyEnglishLetters` function, enhancing the input validation logic to support usernames with English letters, numbers, hyphens, and underscores. The changes ensure backward compatibility with the previous functionality while updating relevant components and utilities.
* [`src/utils/InputFormats/formats.js`](diffhunk://#diff-c3ac9822238f894ef5db7610a49bcae75671b76546eded88e2a6a4c68d0b42b5L26-R28): Replaced the `allowOnlyEnglishLetters` function with a new `formatUsername` function that allows English letters, numbers, hyphens, and underscores. Updated the input formatting logic to prioritize `usernameFormat` over `englishOnly` for backward compatibility. …

ML8-17 Username Input Customization

---

src/app/layout.js

This pull request adds Google Tag Manager (GTM) integration to the `RootLayout` component in the `src/app/layout.js` file. The changes include embedding GTM scripts and a noscript fallback for better analytics tracking.
* [`src/app/layout.js`](diffhunk://#diff-effae781aec14179efa7c736b6c5421456934f55d2ec95783dda05a1e8605abeR42-R59): Added a `<script>` tag with `dangerouslySetInnerHTML` to initialize GTM, and included a `<noscript>` fallback with an `<iframe>` for GTM to support browsers with JavaScript disabled.

ML8-10 Tag Manager Code - Features

---

public/css/style.css
src/app/globals.css
src/app/layout.js
src/components/ui/Header.jsx
src/components/ui/PulsatingDot.jsx
src/components/ui/buttons/SaveButton.jsx

This pull request introduces several updates across the codebase, including new UI components, CSS enhancements, and code refactoring for improved readability and maintainability. The most significant changes involve the addition of a reusable `PulsatingDot` component, enhancements to CSS styling, and the introduction of optional chaining in data mapping logic.
* **Reusable Pulsating Dot Component**: Added a new `PulsatingDot` React component that renders a customizable pulsating dot with configurable size, color, and animation duration. This component is reusable and includes inline styles and keyframe animations. (`src/components/ui/PulsatingDot.jsx`)
* **Save Button Update**: Updated the `SaveButton` component to include a new `disabled` prop, which adds an additional condition to …

ML-9 Changes

---

src/components/ui/forms/EditProfile/AccountForm.jsx
src/components/ui/forms/EditProfile/AdditionalInfoForm.jsx
src/components/ui/forms/EditProfile/BasicInfoForm.jsx
src/components/ui/forms/EditProfile/PresentationForm.jsx
src/lib/profile/update.js
src/lib/validation/profile.js

This pull request focuses on restructuring and redistributing form fields across different components in the profile editing UI, while also cleaning up unused fields and improving validation logic. Key changes include moving the `phone`, `rate`, and `commencement` fields to more appropriate forms and updating the corresponding logic and UI elements.
* **`AccountForm` Updates (`src/components/ui/forms/EditProfile/AccountForm.jsx`):**
- Removed `phone` field and its associated logic to streamline the form. (`[[1]](diffhunk://#diff-75a8d8be00188cb6c2d141b18f2ba64f125c37bc818ead037850ca24e182413bL30-L50)`, `[[2]](diffhunk://#diff-75a8d8be00188cb6c2d141b18f2ba64f125c37bc818ead037850ca24e182413bL273-L286)`)
* **`AdditionalInfoForm` Updates …

ML9-7 Rearrange Profile Fields - Features

---

src/lib/auth/index.js
src/lib/client/operations.js
src/lib/validation/auth.js
src/utils/errors.js

This pull request introduces several changes aimed at improving error handling, enhancing user feedback with localized error messages, and cleaning up unused or commented-out code. The most significant updates include adding a translation map for common Strapi errors, updating error handling in GraphQL operations, and localizing validation error messages.
* [`src/lib/client/operations.js`](diffhunk://#diff-3f387ce2d31c4defcbb60ceae1a582057889e69b287af8a13756464633bd5ecbL223-R254): Enhanced error handling in `postData` and `putData` functions by introducing localized error messages using a new `strapiErrorTranslations` map. This ensures that users receive more meaningful and user-friendly error feedback. [[1]](diffhunk://#diff-3f387ce2d31c4defcbb60ceae1a582057889e69b287af8a13756464633bd5ecb …

ML9-27 Login Errors Translate - Fixes

---

src/components/ui/Archives/Freelancers/ContentSkeleton.jsx
src/components/ui/Archives/Freelancers/FreelancerGridSkeleton.jsx
src/components/ui/Archives/Freelancers/FreelancersArchive.jsx
src/components/ui/Archives/Services/ServiceGridSkeleton.jsx
src/components/ui/Archives/Services/ServicesArchive.jsx
src/components/ui/suspense/Pending.jsx

This pull request refactors the frontend components for handling skeleton loaders, removes unused filters, and replaces the `Suspense` component with a custom `Pending` component for better control over loading states. It also includes visual adjustments to skeleton loaders for a more consistent UI.
* Updated the height and styles of skeleton loaders in `ContentSkeleton`, `FreelancerGridSkeleton`, and `ServiceGridSkeleton` to improve visual consistency. (`[[1]](diffhunk://#diff-67885ae7414089596253410a572cd09b77193450d5fbd51de58114bed084d648L15-R15)`, `[[2]](diffhunk://#diff-f1adedcb01e6d5fc6c420ce7f76aff51dcab6bb1fc6533e16b1a7f93c52546f1L11-R16)`, `[[3]](diffhunk://#diff-fb560b0de759bbcff472605c7515a2294ac52ecfde251d908132bbd4ef0bf582L12-R14)`)
* Removed unused filters (`Rate`, …

ML9-21 Skeleton filters loading - Features

---

src/lib/graphql/queries/main/taxonomies/service/index.js

This pull request updates the GraphQL query `SUBDIVISIONS_FOR_FILTERED_SERVICES` in `src/lib/graphql/queries/main/taxonomies/service/index.js` to improve filtering logic and streamline the structure for better readability and functionality. The most important changes include restructuring filter conditions and consolidating redundant logic.
* Added new filter conditions for `price` (range between `$min` and `$max`), `time` (less than or equal to `$time`), `status` (must be `"Active"`), `tags` (must match `$tags`), and `freelancer` (must have a non-null `id` and be verified if `$verified` is true). These filters are now grouped together for clarity.
* Consolidated redundant logic by removing duplicate filters for `price`, `time`, `freelancer`, `status`, and `tags` in the `or` condition. …

ML10-13 Subdivisions in Category Field #236

---

src/actions/auth/login.js
src/actions/tenant/onboarding.js
src/actions/tenant/status.js
src/components/form/form-auth-login.jsx

This pull request focuses on simplifying the codebase by removing or commenting out unused functionality related to redirection and revalidation paths. It also includes minor adjustments to streamline the login process and onboarding flow.
* [`src/actions/auth/login.js`](diffhunk://#diff-0f46d5a4e2981304c6368bc3a89285e5f6b1013dc1edbf54ef3181158fae2ee7L42-R42): Updated the redirect path after login from `/dashboard/profile` to `/dashboard` for a more generic dashboard routing.
* [`src/actions/tenant/onboarding.js`](diffhunk://#diff-27388d5028109cfbd12b3477be229ac4f0dafd11a4eb5c4e2884bb535e7d2352L341-L351): Commented out revalidation paths (`/dashboard/profile` and `/dashboard/start`) to reduce unnecessary revalidation during onboarding flow.
* …

ML10-1 Debugging Onboarding

---

src/components/form/form-auth-login.jsx

This pull request makes changes to the `LoginForm` component in `src/components/form/form-auth-login.jsx` to improve the handling of post-login behavior. The most notable updates include replacing `useRouter` with a full page reload for middleware triggering and removing unused imports.
* [`src/components/form/form-auth-login.jsx`](diffhunk://#diff-f93f9d9a2ecee45b8b51975b09c285526cfb8c31cdb00b8aa1453bf98d34313fL18-R22): Removed `useRouter` and replaced `router.replace('/login')` with `window.location.reload()` to trigger middleware using a full page refresh after a successful login. This simplifies the logic and ensures middleware execution.
* [`src/components/form/form-auth-login.jsx`](diffhunk://#diff-f93f9d9a2ecee45b8b51975b09c285526cfb8c31cdb00b8aa1453bf98d34313fL8): Removed the …

ML10-1 Login Reload

---

src/components/content/content-freelancer.jsx
src/components/content/content-service.jsx
src/components/parts/description-block.jsx
src/components/parts/index.js

Create DescriptionBlock component and switched it with service and terms sections.

ML10-18 Profile Description Missing #236

---

src/app/(auth)/auth/google/complete/page.jsx
src/app/(auth)/auth/google/connect/page.jsx
src/app/(auth)/auth/google/error/page.jsx
src/app/(auth)/auth/google/select-type/page.jsx
src/app/(auth)/auth/google/success/page.jsx
src/components/button/google-login-button.jsx
src/components/form/form-auth-login.jsx
src/components/input/input-auth-options.jsx
src/components/wrapper/body.jsx

This pull request introduces a series of new components and pages to enhance the Google OAuth flow, including support for different account types, error handling, and success states. The changes primarily focus on user experience improvements and integration with backend APIs for account creation and authentication.
* **Professional Registration Completion Page**: Added `GoogleCompleteMinimal` component in `src/app/(auth)/auth/google/complete/page.jsx` to handle the final step of professional account creation. This includes form validation, backend API integration, and dynamic redirection based on account type.
* **Account Type Selection Page**: Added `GoogleSelectType` component in `src/app/(auth)/auth/google/select-type/page.jsx` to allow users to choose between simple and professional …

ML10-2 Auth

---

src/app/(auth)/auth/google/complete/page.jsx
src/app/(auth)/auth/google/connect/page.jsx
src/app/(auth)/auth/google/select-type/page.jsx
src/components/button/google-login-button.jsx

This pull request updates several components to improve flexibility in handling environment variables for the Strapi API URL. The changes replace hardcoded references to `process.env.NEXT_PUBLIC_STRAPI_URL` with a fallback to `process.env.STRAPI_URL`, ensuring compatibility with different deployment configurations.
* **Authentication Flows:**
- Updated the API URL in `GoogleCompleteMinimalContent` to use `process.env.NEXT_PUBLIC_STRAPI_URL || process.env.STRAPI_URL`. (`src/app/(auth)/auth/google/complete/page.jsx`, [src/app/(auth)/auth/google/complete/page.jsxL139-R139](diffhunk://#diff-b4d697a94262708ac9faf7a7ddbe3b3ed6bd0caa762b7bc9191854a39d91270dL139-R139))
- Modified multiple instances of the API URL in `GoogleRedirectContent` to include the fallback to `process.env.STRAPI_URL`. …

ML10-2 Production Env Variables

---

src/app/(auth)/auth/google/complete/page.jsx
src/app/(auth)/auth/google/connect/page.jsx
src/app/globals.css
src/components/button/google-login-button.jsx
src/components/content/content-dashboard.jsx
src/components/form/form-auth-login.jsx
src/components/form/form-auth-register.jsx
src/components/input/input-auth-options.jsx

This pull request introduces updates to improve Google OAuth integration, enhance user experience, and clean up the codebase. The most significant changes include adjustments to the Google login button's styling and placement, updates to user data handling, and minor text and placeholder modifications.
* Added a new `GoogleLoginButton` component to the registration form (`RegisterForm`) for streamlined Google sign-up, including a divider for visual separation. [[1]](diffhunk://#diff-47814135a8dbf4b8ffa75479f312a79758fcf81409812f36630826e3067f36e4R13) [[2]](diffhunk://#diff-47814135a8dbf4b8ffa75479f312a79758fcf81409812f36630826e3067f36e4R184-R199)
* Removed the Google OAuth button from the `AuthTypeOptions` component, consolidating its functionality into other areas of the application. …

ML10 | Auth *Fixes #239

---

src/components/form/form-profile-basic-info.jsx

This pull request removes explanatory text and a checklist from the `BasicInfoForm` component in `src/components/form/form-profile-basic-info.jsx`. These changes simplify the form's UI by eliminating redundant or non-essential information.
* Removed a paragraph and a checklist describing the requirements for public profile visibility, including profile image, category/subcategory, and service provision methods. This reduces visual clutter in the `BasicInfoForm` component.

ML10-25 Remove Profile Status Message #236

---

src/actions/shared/user.js
src/app/api/security/log-mismatch/route.js
src/components/wrapper/wrapper-dashboard-active.jsx
src/lib/cache/config.js
src/lib/client/operations.js

This pull request introduces critical security enhancements to prevent cross-user data leakage and ensure data integrity in user-related operations. The changes include stricter caching policies, improved validation and logging, and enhanced handling of user-specific queries. Below is a summary of the most important changes grouped by theme.
* **Caching Policy Updates**:
- Disabled caching for user-specific data in `CACHE_CONFIG`, including the `USERS` and `SAVED_STATUS` configurations, to prevent cross-user data leakage. (`src/lib/cache/config.js`, [[1]](diffhunk://#diff-dc4699fd7e18eb630844d1029b93ae71404176f1ddfc94f68061aa168a2be58bR6-R10) [[2]](diffhunk://#diff-dc4699fd7e18eb630844d1029b93ae71404176f1ddfc94f68061aa168a2be58bL47-R50)
- Simplified the caching logic in `getDataInternal` …

ML10-28 Auth Cache & User Data Integrity

---

src/actions/auth/confirm-token.js
src/components/form/form-auth-email-confirmation.jsx

This pull request introduces enhancements to the email confirmation process, focusing on improved error handling, user experience, and authentication checks. The most significant changes include adding localized error messages, integrating authentication checks before processing tokens, and refining the user interface to handle various states like success, error, and already authenticated.
* [`src/actions/auth/confirm-token.js`](diffhunk://#diff-392f80b96a554e586083cf0a950e743588d61649f9f0f5d443796bdb597d065aL21-R21): Updated error messages to localized Greek versions and added specific error handling for network issues, timeouts, and unexpected errors. [[1]](diffhunk://#diff-392f80b96a554e586083cf0a950e743588d61649f9f0f5d443796bdb597d065aL21-R21) …

ML10-29 Fix Email Confirmation

---

src/components/banner/banner-cookies.jsx
src/components/hero/hero-home-content.jsx
src/components/hero/hero-home-popular-searches.jsx
src/components/hero/hero-home-search-bar.jsx

This pull request introduces significant updates to the `CookiesBanner` component, focusing on improving user experience, performance, and rendering logic, along with minor design refinements in other components. The main changes include delaying the rendering of the cookie banner, ensuring it only appears under specific conditions, and simplifying animations and styles across various components.
* Introduced a `canRender` state to completely prevent rendering of the cookie banner until specific conditions are met, including a minimum 10-second delay and an additional 2-second delay before showing the banner. (`src/components/banner/banner-cookies.jsx`, [src/components/banner/banner-cookies.jsxR14-R82](diffhunk://#diff-d0b158883cb564d56e019cd16764134e76548aae998221d51c3b6766747bbacfR14-R82 …

ML11-7 Largest Contentful Paint element #274

---

src/components/wrapper/body.jsx

This pull request refactors the `Body` component in `src/components/wrapper/body.jsx` to improve the user experience by ensuring basic styles are applied before full mounting and addressing hydration issues. The most important changes include modifying how body classes are determined and ensuring consistent rendering of children elements.
* Updated the `getBodyClasses` function to allow basic classes (`bgc-thm4 mm-wrapper mm-wrapper--position-left-front`) to be applied even before the component is fully mounted, improving the perceived load time for users.
* Changed the rendering logic to always render `children` inside a `<div>` element with a `data-mounted` attribute, instead of conditionally rendering `children` only when mounted. This ensures proper hydration and avoids potential …

ML11-7 LCP Fixing - Body 11s delay #274

---

next.config.js
src/app/(dashboard)/dashboard/start/page.jsx
src/app/(home)/page.jsx
src/app/layout.js
src/components/content/content-freelancer.jsx
src/components/content/content-service.jsx
src/components/dynamic/dynamic-add-review-form.jsx
src/components/dynamic/dynamic-all-taxonomies.jsx
src/components/dynamic/dynamic-bottom-to-top.jsx
src/components/dynamic/dynamic-cookies-banner.jsx
src/components/dynamic/dynamic-features.jsx
src/components/dynamic/dynamic-freelancer-report-form.jsx
src/components/dynamic/dynamic-mega-menu.jsx
src/components/dynamic/dynamic-nav-menu-mobile.jsx
src/components/dynamic/dynamic-service-featured-files.jsx
src/components/dynamic/dynamic-service-report-form.jsx
src/components/dynamic/dynamic-start-chat-modal.jsx
src/components/dynamic/dynamic-stats.jsx
src/components/dynamic/index.js
src/components/global/bootstrap.jsx
src/components/header/header.jsx

This pull request introduces significant changes to enhance the application's performance and user experience by dynamically loading components. It replaces several static imports with dynamic imports to defer loading of less critical components, optimizing server-side rendering (SSR) and improving page load times. Additionally, it includes minor adjustments to styling and structure in certain components.
[ML11-4 Dynamic Imports - Reduce JavaScript execution time](https://github.com/damigrowth/nextjs/pull/289/commits/23047b32d9295215cabab4c52da76dee7fa906b6) https://github.com/damigrowth/nextjs/issues/274
[ML11-4 optimizePackageImports - Reduce JavaScript execution time](https://github.com/damigrowth/nextjs/pull/289/commits/d53d4ab2d04cf2a4b9fb3044711f2f01dae7625a) …

ML11-4 Reduce JavaScript execution time #274

---

src/components/card/card-service-files.jsx
src/components/card/card-service-media-slider.jsx
src/components/parts/service-featured-files.jsx
src/components/parts/taxonomies-swiper.jsx
src/components/section/section-featured-categories-swiper.jsx
src/components/section/section-testimonials-stats.jsx
src/components/swiper/index.js
src/components/swiper/swiper-optimized.jsx
src/components/wrapper/wrapper-featured-freelancers-client.jsx
src/components/wrapper/wrapper-featured-freelancers.jsx
src/components/wrapper/wrapper-featured-services-client.jsx

This pull request introduces a significant refactor to the Swiper integration across multiple components to optimize performance and improve maintainability. The changes centralize Swiper module imports, enable dynamic module loading, and introduce fallback UI elements (e.g., spinners) while Swiper modules are being loaded. The key updates include creating a new `swiper-optimized` module, replacing static imports with dynamic ones, and updating all components that use Swiper to leverage these improvements.
* [`src/components/swiper/index.js`](diffhunk://#diff-e785ef3c0fd28d3f863d052564d14afed658b79e42b79b77169881544a393196R1-R17): Added exports for `Swiper`, `SwiperSlide`, and utility functions from the new `swiper-optimized` module to centralize Swiper-related logic.
* …

ML11-4 Swiper Optimized #274

---

src/actions/schema/basic.js
src/components/form/form-onboarding.jsx
src/components/header/header-dashboard.jsx
src/components/header/header-onboarding.jsx
src/components/input/input-media-gallery.jsx
src/components/input/input-media-upload.jsx
src/components/input/input-profile-image.jsx
src/components/input/input-service-gallery.jsx
src/styles/globals.css
src/utils/media-validation.js

This pull request introduces significant enhancements to media validation, error handling, and UI improvements across various components. The changes focus on replacing hardcoded logic with reusable utilities, improving file type detection, and addressing platform-specific issues such as iOS Safari compatibility. Below is a breakdown of the most important changes:
* Replaced hardcoded file type checks with `validateFileType` utility for more robust and reusable validation in `MediaGallery`, `MediaUpload`, `ProfileImageInput`, and `ServiceGallery` components. This includes support for specific media types (`image`, `video`, `audio`) and profile image restrictions. [[1]](diffhunk://#diff-eee0b14ec8ab9886e75c4b567b754e6fc1a70969cabe752013f9aa390893bf11L239-R239) …

ML11-27 Onboarding errors not showing
